### ISSUE TITLE
Upgrade Supabase to supabase-js version 1.0 form auth interface changes

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/playground-auth#11]
See: https://github.com/redwoodjs/redwood/issues/1426

Supabase has [released v1.0](https://supabase.io/blog/2020/10/30/improved-dx/)

Some changes are:

* signup() is now signUp() and email / password is passed as an object
* logout() is now signOut()
* login() is now signIn()

And

- Errors are now returned and not thrown
- Auth now uses `@supabase/gotrue-js` interface (hence the above)

**Comment by kiwicopple** [comment]
Some more details: 

- Supabase now has magic links, email, and OAuth logins. https://supabase.io/docs/client/auth-signin/#examples
- Supabase has an "auth change listener" which is useful for whenever a session is restored from local storage: https://supabase.io/docs/client/auth-onauthstatechange

I had a quick look at the Redwood implementation for Firebase auth, which was was [recently improved](https://github.com/redwoodjs/redwood/pull/1412#event-3959279810) with similar functionality. It could be a good guide for the changes required in this issue.

Supabase has a React example [here](https://github.com/supabase/supabase/blob/master/examples/todo-next-js/components/Auth.js) which shows how to use the auth functionality. I haven't had a chance to build Redwood examples, but I hope to have some time next week.

**Comment by Tobbe** [comment]
Initial Supabase 1.0 support has now landed (https://github.com/redwoodjs/redwood/pull/1536) so as soon as the next release of RW is out we need to update our example here.

OAuth etc will come in future PRs.

**Comment by dthyresson** [comment]
Need to add `SUPABASE_JWT_SECRET` to

https://github.com/redwoodjs/playground-auth/blob/945367336ae055573d6b326dbdf2b8b33d2a179d/web/src/components/Supabase/Supabase.js#L7

and ensure this value is added to the Netlify envars.
