### ISSUE TITLE
Add third party auth providers for Supabase 

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/playground-auth#26]
Add third party auth option for Supabase playground item

Implement similar to current Firebase item with provider dropdown
![image](https://user-images.githubusercontent.com/9841162/114898654-2a613b00-9dc7-11eb-930b-19aedebc41ce.png)

I'd like to take this on as a challenge!

**Comment by morganmspencer** [comment]
I might be wrong but I think once you do this for GitHub then the rest of the providers can be added. I think you just have to pass in the provider name to differentiate. So, you setting this up for GitHub could actually be for all of them! 😀

**Comment by clairefro** [comment]
to infinity and beyond!

**Comment by clairefro** [comment]
oopsie just did more research and found this might be [already in development](https://github.com/redwoodjs/playground-auth/pull/19) 

is this feature already being addressed @dthyresson ?

**Comment by dthyresson** [comment]
@clairefro the Supabase auth client can now login with OAuth and I have tested GitHub in another app.

But, the UI to do so is not there but should:

* let you pick an OAuth provider
* optionally redirect to one of a few new "destination" pages as a result of the redirect callback

I've added you to the Supabase team for this (and some other RW) app so you can see and setup other providers as needed.

Currently I have GitHub and Google setup to test.

**Comment by dthyresson** [comment]
@clairefro For the UI might want to try the Social options shown in

https://tailwindui.com/components/application-ui/forms/sign-in-forms
