### ISSUE TITLE
UI: Improve UX by adding Tabs per Provider

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/playground-auth#29]
From @morganmspencer:

> My thought for future improvements is to allow users to tab through the different providers so only one would be on screen at a time. This could be beneficial as the list of providers grows. 

Now that this app has Tailwind by default, let's add this structure.

Let's use https://headlessui.dev/ for the TW react components when possible.

I have access to [TailwindUI components](https://tailwindui.com), so if there is a particular screen or component there that you need the code to do, let me know.

**Comment by morganmspencer** [comment]
I also have access to Tailwind UI if anyone needs it. Excited to use the new Headless UI components!

**Comment by morganmspencer** [comment]
Currently working on this. Any ideas on what would be better: tabs that lead to individual pages for each provider or URL params? I feel like the switching pages aspect would alleviate any redirect URL issues. Unless some are required to go to the home page.

**Comment by dthyresson** [comment]
> Currently working on this. Any ideas on what would be better: tabs that lead to individual pages for each provider or URL params? I feel like the switching pages aspect would alleviate any redirect URL issues. Unless some are required to go to the home page.

@morganmspencer I don't have a particular preference but I think you're right in that separate pages may make in easier for when a callback returns -- it may not have the info needed to select the provider's tab. Thus, a page per provider is worth a try.

Let's try it and see how it feels to use.
