### ISSUE TITLE
On main view with all providers, add authenticated badge indicator

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/playground-auth#35]
![image](https://user-images.githubusercontent.com/1051633/115149060-50d5df00-a030-11eb-8e39-fb4de9456a60.png)

Since one can be logged in/authenticated to multiple providers, it might be nice to show an Authenticated status in each provider box, section. 

You might be able to reuse

https://github.com/redwoodjs/playground-auth/blob/main/web/src/components/Badge/Badge.js

but wrap it in the AuthProvider needed:

`<AuthProvider client={supabase} type="supabase">`

But that would require creating a client per box too, which is fine.

The "not logged in" or unauthenticated would be a nice call-to-action to then try to sign in/up.

**Comment by morganmspencer** [comment]
I'm happy to take this on if y'all need help!

**Comment by WizardSource** [comment]
<img width="1680" alt="Screen Shot 2021-04-18 at 3 45 55 PM" src="https://user-images.githubusercontent.com/7276145/115158906-8e516100-a05e-11eb-9ed6-043610cfb8ed.png">
**Idea:** AuthResults _(to display results in a separate container)_

**Comment by dthyresson** [comment]
> <img alt="Screen Shot 2021-04-18 at 3 45 55 PM" width="1680" src="https://user-images.githubusercontent.com/7276145/115158906-8e516100-a05e-11eb-9ed6-043610cfb8ed.png">
> 
> Didn't want to open a new issue for this but just worked on an idea for AuthResults to display in a separate container.

@WizardSource Thanks! That could definitely help readability.

We have 2 helpers to let you know auth is working ok: the results abs a refresh token poll. Both could use some love

If you push a PR we can review
