### ISSUE TITLE
Idea: Show code samples like in RedwoodJS.com to reveal how to setup and use a provider

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/playground-auth#42]
Idea: Show code samples like in RedwoodJS.com to reveal how to setup and use a provider

Similar to: 

![image](https://user-images.githubusercontent.com/1051633/115162873-05ddbb00-a074-11eb-9b95-16e23f395120.png)

This could be the actual code, but more like an example code snippet.

Maybe have a

![image](https://user-images.githubusercontent.com/1051633/115162903-26a61080-a074-11eb-8d88-352753f8d574.png)

similar to TailwindUI where preview is "try"? and code is the example?

**Comment by morganmspencer** [comment]
Love this idea! One of my favorite parts about TailwindUI. Makes it really easy! I would think it could go between the select provider and the login on the provider page.

**Comment by morganmspencer** [comment]
Also happy to help on this, but don't want to keep scooping up all these issue if someone else wants it 😂

**Comment by dthyresson** [comment]
> Also happy to help on this

I'll keep assigning if you keep asking ;) Just let me know what you want to work on or not and if it gets too much, you can always say no.

**Comment by dthyresson** [comment]
You can just have some sample code in there that is close and we can improve. I think we'll need to address the Issue about error/exception handing in the code samples for a thorough example: https://github.com/redwoodjs/playground-auth/issues/39

**Comment by morganmspencer** [comment]
I've also been wondering in general, but is relevant here, should we be using `@redwoodjs/forms` for these. I think it might make sense in some instances, but I guess there would have to be a switch for `onSubmit` to distinguish between login, sign up, and third-party providers.

**Comment by dthyresson** [comment]
> should we be using `@redwoodjs/forms`

I'm not sure - redwood/forms does have some error handling, but that relies a bunch on the GraphQL/api sending back a formatted error of a particular type. Not sure it is that valuable here, but what do you think @Tobbe? I am happy w/ TW forms in this case, myself.
