### ISSUE TITLE
Add eslint?

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/playground-auth#50]
Am I the only one seeing funky linting errors? like 

`'process' is not defined. eslint (no-undef)`

![image](https://user-images.githubusercontent.com/9841162/115326300-f036c700-a141-11eb-871f-127ad01a4096.png)

Noticed we don't have an eslintrc file. We could add one and apply fixes project wide

**Comment by morganmspencer** [comment]
I've been getting those as well with the same instance. Also using require statements does the same error

**Comment by clairefro** [comment]
Oh, we do have eslint via redwood :) 

But I think the web side isn't expecting `process` or `require` because the env `node` isn't set to true (only `browser` and `es6`). 
https://github.com/redwoodjs/redwood/blob/main/packages/eslint-config/index.js#L43

maybe we need to extend to add `common: true` or `node: true`? I'm not real familiar...

**Comment by dthyresson** [comment]
@clairefro I have upgraded this app to v0.31 which should have the eslint fixes in.

If this is no longer an issue, please close. Thanks!

**Comment by dthyresson** [comment]
Closing item out.
