### ISSUE TITLE
[Suggestion] Update code samples to include Auth Provider setup

### ISSUE THREAD

**Issue by dac09** [redwoodjs/playground-auth#53]
It would be awesome if we could include installation instructions for each Auth provider. Like this the info here: https://redwoodjs.com/docs/authentication#netlify-identity-widget

Ideally we'd do this without duplicating the code, so maybe linking to the docs might be better option?

**Comment by morganmspencer** [comment]
Hey @dac09 I actually just added this feature on the code tab for each provider. Perhaps it should be included on the demo tab as well. I believe the PR just got merged by @dthyresson

**Comment by dac09** [comment]
Hey @morganmspencer thanks for the awesome work so far! I actually meant the setup instructions, for setting it up on your redwood app.

I think the current code block shows how you would write up the login/signup part, but not the other config you need to do first :)

**Comment by morganmspencer** [comment]
There should be a link above the code block that leads to the authentication docs. Is it not there?

![image](https://user-images.githubusercontent.com/10109983/115451680-807d1680-a1eb-11eb-835b-d0c1aee72400.png)

**Comment by dac09** [comment]
AH! I didn't spot that. The link probably just needs to be more prominent, maybe something like Step 1, Step 2
