### ISSUE TITLE
Race condition between Azure and Google w/Supabase

### ISSUE THREAD

**Issue by ajoslin103** [redwoodjs/playground-auth#73]
as per: https://community.redwoodjs.com/t/auth-playground-broken-for-google-w-supabase/2355

> 
> dthyresson
> RedwoodJS Core Team
> @ajoslin103 Yes, this is known issue unfortunately that crept back in.
> The issues is that this Playground has a dozen of so auth clients, and unfortunately there can be a race condition between Azue Active Directory and Supabase when handling the OAuth callback.
> So, here, Azure picks it up ahead of Supabase.
> We fixed in some time ago by using a specific Supabase callback page, but perhaps that setting got changed in the Supabase Auth or the GitHub app config.
> Could you please write up an issue in the repo, as these types of issues and bugs will get lost in the Forum vs the issues list.
> 

![Screen Shot 2021-08-10 at 10 12 32 PM](https://user-images.githubusercontent.com/443893/129102264-68d8b034-344f-479b-bdac-7d37c5869d4c.png)

**Comment by dthyresson** [comment]
Even with 38.1- canary and Azure, seeing issues with Clerk setup and also Supabase and Netlify interactions.

Will want to wait for Clerk updates.
